name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * 0"

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
            
      - name: "📚  Hashnode Updater"
        uses: "phonghaw2/action-hashnode-blog@main"
        with:
          BLOG_URL: "phonghaw2coder.hashnode.dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
