name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron:  "* * * * *"

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
            
      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "Phonghaw2"
          COUNT: 5
          FILE: "README.md"
          STYLE: "list"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
